#!/bin/bash
#
# Enable https.

export TMP=/tmp/https

cd /home/ec2-user/generate-certs &> $TMP-1400

cp nginx_https.conf nginx_https_local.conf &> $TMP-1450

sed -i "s/KIBANASPACE/blog/" nginx_https_local.conf &> $TMP-1500

sudo cp nginx_https_local.conf /etc/nginx/nginx.conf &> $TMP-1600

sudo service nginx restart &> $TMP-1700
